### PR TITLE
change filenames

### LINKED ISSUE #1: change the directory of the fig files
As I used a specific version of osloMet beamer template. 
the names remain what they were in the first implementation, it would be a good idea to change them and the corresponding latex code

### PR DESCRIPTION
**Pull request by NevilleMthw**
Resolves #1.

### CODE REVIEW

**Comment by erfanhamdi** [comment]
Could you please `git pull` the latest version and then have a PR for just #1 ?

**Comment by NevilleMthw** [comment]
Yes, I will do that. Just created the PR immediately after your recent commits.

**Comment by erfanhamdi** [comment]
I have to find a way so that github checks the PRs before merging them🤔

**Comment by NevilleMthw** [comment]
@erfanhamdi You can check this? https://docs.lacework.com/iac/enforce-merge-checks

**Comment by erfanhamdi** [comment]
thanks, lets see how that works now

**Comment by NevilleMthw** [comment]
Let me know if you have it setup through the guide and I can submit a PR to check if it is working.

**Comment by erfanhamdi** [comment]
yeah I have set it up 
could you please do that?

**Comment by NevilleMthw** [comment]
Sure.

**Pull request merged**
